{{- if and .Values.secret.create (not .Values.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grob.secretName" . }}
  labels:
    {{- include "grob.labels" . | nindent 4 }}
type: Opaque
{{- with .Values.secret.data }}
stringData:
  {{- range $k, $v := . }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
{{- end }}
